package AMI_DATA_COLLECTION;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({
	
	AMI_ACQUISITION_TASK_FUNCTION_001.class,
	AMI_ACQUISITION_TASK_FUNCTION_003.class,
	AMI_DATA_QUERY_FUNCTION_001.class,
	AMI_DEVICE_MONITOR_FUNCTION_001.class,
	AMI_DEVICE_MONITOR_FUNCTION_002.class,
	AMI_FIIIUP_FUNCTION_001.class,
	AMI_FIIIUP_FUNCTION_002.class,
	
	AMI_FIIIUP_FUNCTION_004.class,
	AMI_FIIIUP_FUNCTION_005.class,
	
	AMI_FILLUP_FUNCTION_006.class,
	AMI_FILLUP_FUNCTION_007.class,
	AMI_FILLUP_FUNCTION_008.class,
	AMI_FILLUP_FUNCTION_009.class,
	AMI_FILLUP_FUNCTION_010.class,
	
	AMI_FILLUP_FUNCTION_015.class,
	AMI_FILLUP_FUNCTION_016.class,
	
	AMI_FILLUP_FUNCTION_021.class,
	AMI_FILLUP_FUNCTION_022.class,
	AMI_FILLUP_FUNCTION_023.class,
	
	AMI_FILLUP_FUNCTION_025.class,
	AMI_FILLUP_FUNCTION_026.class,
	AMI_FILLUP_FUNCTION_027.class,
	
	AMI_METER_READING_FUNCTION_001.class,
	
	AMI_STATISTICS_FUNCTION_001.class,
	AMI_STATISTICS_FUNCTION_002.class,
	AMI_STATISTICS_FUNCTION_003.class,
	AMI_STATISTICS_FUNCTION_004.class,
	AMI_STATISTICS_FUNCTION_005.class,

})

public class AMI_DATA_COLLECTION_MAIN {
	
}
